### ISSUE TITLE
Frontmatter property does not work with emojis

### ISSUE THREAD

**Issue by FlorianWoelki** [FlorianWoelki/obsidian-iconize#284]

**Comment by BorisTheTripper** [comment]
I also feel like it would be nice if it could parse an icon property even if it has flanking colons like `:LiThumbsUp:`. Right now, it will only parse `LiThumbsUp`, i.e. without colons.

The reason I think this would be nice is for those of us who'd like to use this with Dataview, e.g. displaying an note-specific icon in  a table view, which is much easier with the colons present.

**Comment by FlorianWoelki** [comment]
> I also feel like it would be nice if it could parse an icon property even if it has flanking colons like `:LiThumbsUp:`. Right now, it will only parse `LiThumbsUp`, i.e. without colons.
> 
> The reason I think this would be nice is for those of us who'd like to use this with Dataview, e.g. displaying an note-specific icon in a table view, which is much easier with the colons present.

Feel free to create a new issue for that :)

**Comment by FlorianWoelki** [comment]
Has been resolved with [2.7.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.7.1).

**Comment by redactedscribe** [comment]
I took this to mean I could add 🙂 to `icon:` and it would work, but I still see "icon could not be found". What gives @FlorianWoelki?

**Comment by FlorianWoelki** [comment]
> I took this to mean I could add 🙂 to `icon:` and it would work, but I still see "icon could not be found". What gives @FlorianWoelki?
> 
> **Edit:** My bad. This is indeed fixed! I thought I hit update all in Obsidian but instead only updated a single different plugin (I was still on 2.7.0). Now it works!

Nice to hear :)

**Comment by berot3** [comment]
@FlorianWoelki just wanted to let you know that I did the mistake to add the icon first with the new properties-interface, which added the icon as a list... so just a hints up :D

```
icon:
  - 😄
```

which got me this error:

```
plugin:obsidian-icon-folder:5545 TypeError: str.match is not a function
    at Object.isEmoji (plugin:obsidian-icon-folder:2527:13)
    at IconFolderPlugin.eval (plugin:obsidian-icon-folder:5540:36)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-icon-folder:31:71)
    at new Promise (<anonymous>)
    at __awaiter (plugin:obsidian-icon-folder:27:12)
    at eval (plugin:obsidian-icon-folder:5523:79)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:1800309)
    at t.<anonymous> (app.js:1:1792684)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)
eval @ plugin:obsidian-icon-folder:5545
eval @ plugin:obsidian-icon-folder:31
__awaiter @ plugin:obsidian-icon-folder:27
eval @ plugin:obsidian-icon-folder:5523
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
```

of course changing it to a usual `icon: 😄` fixed it.

and thanks a lot for the great work!!!

**Comment by FlorianWoelki** [comment]
> @FlorianWoelki just wanted to let you know that I did the mistake to add the icon first with the new properties-interface, which added the icon as a list... so just a heads up :D
> 
> ```
> icon:
>   - 😄
> ```
> 
> which got me this error:
> 
> ```
> plugin:obsidian-icon-folder:5545 TypeError: str.match is not a function
>     at Object.isEmoji (plugin:obsidian-icon-folder:2527:13)
>     at IconFolderPlugin.eval (plugin:obsidian-icon-folder:5540:36)
>     at Generator.next (<anonymous>)
>     at eval (plugin:obsidian-icon-folder:31:71)
>     at new Promise (<anonymous>)
>     at __awaiter (plugin:obsidian-icon-folder:27:12)
>     at eval (plugin:obsidian-icon-folder:5523:79)
>     at e.tryTrigger (app.js:1:695499)
>     at e.trigger (app.js:1:695432)
>     at t.trigger (app.js:1:1800309)
>     at t.<anonymous> (app.js:1:1792684)
>     at app.js:1:237027
>     at Object.next (app.js:1:237132)
>     at a (app.js:1:235850)
> eval @ plugin:obsidian-icon-folder:5545
> eval @ plugin:obsidian-icon-folder:31
> __awaiter @ plugin:obsidian-icon-folder:27
> eval @ plugin:obsidian-icon-folder:5523
> e.tryTrigger @ app.js:1
> e.trigger @ app.js:1
> t.trigger @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> a @ app.js:1
> ```
> 
> of course changing it to a usual `icon: 😄` fixed it.
> 
> and thanks a lot for the great work!!!

Yeah so the type has to be a text (so not as a list or number) :D 
I'll fix that soon and keep track of it at #290!
