### ISSUE TITLE
Icons in Links are not rendered in read mode

### ISSUE THREAD

**Issue by FlorianWoelki** [FlorianWoelki/obsidian-iconize#409]
See title.

**Comment by FlorianWoelki** [comment]
This issue is now fixed with [v2.11.5](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.5).

**Comment by rx-chris** [comment]
I am afraid that this issue is not completely fixed, at least not for me. (I am running obsidian on Windows 10)

Live Preview (seems to be fine):
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/146159597/2d77ac63-f333-4b3d-a28a-27176353997f)

Reading View (some rendered some not):
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/146159597/d8f6fa91-5c7a-450b-bd1f-2baa56dfb07c)

**Comment by FlorianWoelki** [comment]
> I am afraid that this issue is not completely fixed, at least not for me. (I am running obsidian on Windows 10)
> 
> Live Preview (seems to be fine): ![image](https://private-user-images.githubusercontent.com/146159597/320258961-2d77ac63-f333-4b3d-a28a-27176353997f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzUwODgsIm5iZiI6MTcxMjQ3NDc4OCwicGF0aCI6Ii8xNDYxNTk1OTcvMzIwMjU4OTYxLTJkNzdhYzYzLWYzMzMtNGIzZC1hMjhhLTI3MTc2MzUzOTk3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwNzI2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDMwOTc2MzZjNjc3ZjMzNWRkMDYyMTA4NDYyNTFkZjIyNGU0YWEyZmMzOTQ1ZmVmNDdkMmM3NTk1MGE2ZTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Dopw_Qe3kR2lcYN7sDCk5epO_oIDtIVTuJM5BRlYU0g)
> 
> Reading View (some rendered some not): ![image](https://private-user-images.githubusercontent.com/146159597/320258940-d8f6fa91-5c7a-450b-bd1f-2baa56dfb07c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzUwODgsIm5iZiI6MTcxMjQ3NDc4OCwicGF0aCI6Ii8xNDYxNTk1OTcvMzIwMjU4OTQwLWQ4ZjZmYTkxLTVjN2EtNDUwYi1iZDFmLTJiYWE1NmRmYjA3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwNzI2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmExZWEyZWQzNGQzZTY4OTZhODhkYjE0OTI0ODgxZjY0MWY1ZjczYmRmZjc5MTJkMmFkZTJkYzZkNDNhN2RhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K0cVU3dsWSsiO7OvSDnTub6ynuqYJ-2hhkF4nfWCijc)

would it be possible for you to try this on a completely new vault and provide me with the steps to reproduce the issue?

**Comment by rx-chris** [comment]
Hi @FlorianWoelki. Attached is the zip file containing the test vault with the files that reproduce the issue as shown in the image below.

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/146159597/60568fc3-b777-4170-a28c-2274271695ca)


[TestingVault.zip](https://github.com/FlorianWoelki/obsidian-iconize/files/14896148/TestingVault.zip)
ianWoelki/obsidian-iconize/files/14896146/TestingVault.zip)

**Comment by rx-chris** [comment]
From what I see across my vault in reading view is that when there are multiple links under a header, only the first link is rendered with the frontmatter icon. subsequent links does not render. Hope this helps.
