### ISSUE TITLE
Tweemoji not working at all ? 🤔 

### ISSUE THREAD

**Issue by I-Pch** [FlorianWoelki/obsidian-iconize#412]
**Description**
This is more a question than anything else, as I don't know if it's something from my side or if there's something going on with the Tweemojis 😅, But I just installed `Iconize 2.11.4` in a fairly empty vault and for some unknown reasons, I'm just not able to get emojis appearing as Tweemojis ... and I would like to understand why 😄 ...

I didn't change any of the default settings of Iconize, except setting the `Emoji style` to  `Twemoji` and, just in case, to see if it could help, I also toggled `On` the setting `Icons background check` although, I didn't download any of the `Predefined icon packs` available (I left the `Icon packs folder path` set to `.obsidian/icons` and the folder while being empty, has been created) as I just wanted the emojis 😇 ...

My vault is stored on iCloud and I'm on Mac 😊 .

I've rebooted Obsidian multiple times, rebooted my Mac, switched the note in which I added 2 emojis between the different views (Reading/LP/Source) but all I get are the native MacOS emojis 🤷‍♀️ .

The emojis were added in the note through Iconize, by triggering the dropdown/menu hitting <kbd>:</kbd> on my keyboard and selecting the `:herb:` (🌿) and then the `:sparkles:` (✨) emojis with the setting `Toggle icons while editing notes` being toggled `On` 😊 ...
I specifically chose these 2 emojis because I know for sure how they look like as Tweemojis.

Unless this is not how I'm supposed to add tweemojis or how it works ? 🤔  

I know that my Mac is old and dying but I don't know if this could be the reason's why I can't get Tweemojis (instead of the Native ones) to be displayed/available 🤷‍♀️ ...         

---
**Expected behavior**
Having emojis displayed as Tweemojis I guess 😊 

--- 
**Screenshots**
This is just a the part of Iconize's settings where I set the `Emoji style` to  `Twemoji` 😊  (the rest of the settings weren't modified)

<img width="845" alt="Iconize 2 11 4 - Settings" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/77828085/7e2b5d96-ba17-4baa-8f80-5dca2583abed">

And these are the emojis I see, in `Live Preview` whatever I do ... (which are clearly not tweemojis 🤷‍♀️ )

<img width="699" alt="Not tweemojis" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/77828085/5a521753-27c0-440e-8136-8c46ad3770f1">

---
**Additional context**
The console in the dev tool doesn't seem to pick any errors... 

I'm on `MacOS Big Sur 11.7.10` + `Obsidian  v1.5.11` (Installer `v1.5.8`) + Default Dark Theme + No CSS Snippet and just 1 other plugin 😊 .

**Comment by FlorianWoelki** [comment]
thank you for the detailed report! i am going to fix this asap.

**Comment by I-Pch** [comment]
Thank you so very much in advance 😁 🙌 !

**Comment by FlorianWoelki** [comment]
this issue should be fixed with [v2.11.6](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.6).

**Comment by I-Pch** [comment]
> this issue should be fixed with [v2.11.6](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.6).

I just update Iconize in the vault I used when reporting the issue and I'm sorry, but it seems to be partially fixed (I'm really really sorry 😶 )

The Twemojis do render consistently in Reading mode 🙌 ... 

In Live preview, there's still something strange going on 🤔 ... 

The Twemoji either render or nothing gets render at all ... 
<img width="1385" alt="Twemoji - LP   Reading" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/77828085/262dd2d6-1e1f-4041-a259-aff1f85135e9">

It gets stranger if or when I add a callout and then delete said callout ... after that, all the rendered twemojis are replaced by native emojis in Live Preview and I'm enable to get twemojis in the note again (unless I reboot Obsidian)

(This is me deleting a callout, which leads to apparition of the native emojis in Live Preview 😊 ) 

https://github.com/FlorianWoelki/obsidian-iconize/assets/77828085/0b49654c-66af-461a-8657-c8d05c3ea488

This error appears in the console when I delete the callout
```
app.js:1 RangeError: Invalid range for replacement decoration
    at t.range (app.js:1:362941)
    at eval (build-text-decorations.ts:25:12)
    at Array.map (<anonymous>)
    at buildTextDecorations (build-text-decorations.ts:18:12)
    at IconPlugin.update (icon-in-text.ts:23:28)
    at e.update (app.js:1:374285)
    at e.updatePlugins (app.js:1:471944)
    at e.update (app.js:1:470015)
    at e.dispatchTransactions (app.js:1:466635)
    at e.dispatch (app.js:1:468623)
Ca                   @ app.js:1
e.update             @ app.js:1
e.updatePlugins      @ app.js:1
e.update             @ app.js:1
dispatchTransactions @ app.js:1
e.dispatch           @ app.js:1
wv                   @ app.js:1
Cv                   @ app.js:1
Ev                   @ app.js:1
d                    @ app.js:1
Nl                   @ app.js:1
keydown              @ app.js:1
(anonymous)          @ app.js:1
e.runHandlers        @ app.js:1
e.handleEvent        @ app.js:1
```
I am really awfully sorry to bother you once more with all this 😶 ... But I'm also very grateful for everything you've done 🙌 !

**Comment by FlorianWoelki** [comment]
that's strange. did you test it with the latest version (v2.11.7)? if so, could you please create a new issue, thank you :)

**Comment by I-Pch** [comment]
> that's strange. did you test it with the latest version (v2.11.7)? if so, could you please create a new issue, thank you :)

Oh interesting 🤔 ... 
For some reasons, when I updated Obsidian installed `Iconize v2.11.6` and when I look for Iconize in the Community plugins, the only one I seem to be able to install is `Iconize v2.11.6` 😅 ...

<img width="1098" alt="Iconize 2-11-6" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/77828085/cd78b376-3d32-45dd-a292-4be088b43c99">

**Comment by FlorianWoelki** [comment]
haha I am not sure how the internals of obsidian work. so you might just wait :D

**Comment by I-Pch** [comment]
I've finally got `Iconize v2.11.7` 😄 ... 

I'll test it out tomorrow 😊  (and open a new issue if necessary 🍀 ) 

Thank you 😁
