### ISSUE TITLE
Icons not reliably rendering

### ISSUE THREAD

**Issue by mitchmeister** [FlorianWoelki/obsidian-iconize#415]
**Describe the bug**
I have one Obsidian page with about 4 dataviews on it & on my desktop (MacOS) several of the icons don't render (see screenshot below).  Works fine on mobile (iPhone).  If I cursor into the Dataview code & out of it again then the icons will render but they never all consistently render on page load.

**Screenshots**
<img width="834" alt="SCR-20240403-muas" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/6250875/2c85f067-d504-4537-a41e-b1ac77a63adc">

These are my settings

![SCR-20240403-mwnh](https://github.com/FlorianWoelki/obsidian-iconize/assets/6250875/18e1726f-b4b0-4e8b-9bac-ce13c6a2dcfa)

Really appreciate the plugin, thank you for your ongoing support of it.

Appreciate any insight.

**Comment by kaelri** [comment]
This may be related to what I’m seeing today. Icon codes are rendering inconsistent/intermittently throughout the interface. I’m on Obsidian 1.5.12 / Iconize 2.11.5.
<img width="723" alt="Screenshot 2024-04-04 at 10 43 22 AM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/826292/71ca2186-857c-43d8-a664-ef122533bac2">
<img width="277" alt="Screenshot 2024-04-04 at 10 43 00 AM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/826292/86d35528-6d01-468d-8a86-70fd757142a8">

**Comment by kaelri** [comment]
Want to note that my issue has been resolved in the most recent update. OP might want to re-check!

**Comment by FlorianWoelki** [comment]
> Want to note that my issue has been resolved in the most recent update. OP might want to re-check!

thanks for the reply. let's see if it's fixed.

**Comment by mitchmeister** [comment]
This release fixes my dataview issues since .6 but bullet points still missing.

**Comment by FlorianWoelki** [comment]
This is potentially fixed in the newest release. I'll close this issue for now. Feel free to create a new one, if needed.

Additionally, if you have syncing issues, I recommend reading [this guide](https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html#lucide-icons) which was also recently released.

**Comment by mitchmeister** [comment]
seems to be fixed.  Thanks 🙏🏻
