### ISSUE TITLE
Multiple Icons are visible when the note is linked and aliased on another Note

### ISSUE THREAD

**Issue by mayeenulislam** [FlorianWoelki/obsidian-iconize#445]
**Describe the bug**
Multiple Icons are visible when the note is linked **and aliased** on another Note

**To Reproduce**
Please note, I placed emojis here to show where the icons appear. In reality, I used the Font Awesome Solid icons for my notes.

There are two ways links work in Obsidian as I found so far:

**ONE**
If you start typing `[[` the notes will appear and if you choose the note from the dropdown, the link will be like below:
```markdown
[[💁‍♂️../../Profile/Someone Awesome|💁‍♂️Someone Awesome]]
```
If you place out your cursor from the line the icons appear like below:
[💁‍♂️💁‍♂️Someone Awesome](#)

**TWO**
If you drag & drop a note into another, that appears like the below:
[💁‍♂️../../Someone Awesome](#)
In this case, the icon is visible once, but the path is visible. We can easily solve this by aliasing the link:
```markdown
[[💁‍♂️../../Profile/Someone Awesome|Awesome]]
```
And that works, but if you try to type the **title of the note**, the icon appears double:
```markdown
[[💁‍♂️../../Profile/Someone Awesome|💁‍♂️Someone Awesome]]
```
[💁‍♂️💁‍♂️Someone Awesome](#)

**Expected behavior**
For each file, the icon should be visible only once
[💁‍♂️Someone Awesome](#)

**Comment by FlorianWoelki** [comment]
thanks for reporting this issue. unfortunately, I am not able to reproduce this issue. could it be fixed with [v2.11.10](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.10)?

**Comment by mayeenulislam** [comment]
The issue persists on Mac Sonoma 14.1.1 with Iconize 2.11.11 and Obsidian 1.5.12. Here's a GIF:
![Apr-14-2024 16-09-28](https://github.com/FlorianWoelki/obsidian-iconize/assets/4551598/185e0d54-faa8-4f9c-845b-a1c0aa5030bd)

**Comment by FlorianWoelki** [comment]
> The issue persists on Mac Sonoma 14.1.1 with Iconize 2.11.11 and Obsidian 1.5.12. Here's a GIF: ![Apr-14-2024 16-09-28](https://private-user-images.githubusercontent.com/4551598/322263461-185e0d54-faa8-4f9c-845b-a1c0aa5030bd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTAzMjYsIm5iZiI6MTcxMzA5MDAyNiwicGF0aCI6Ii80NTUxNTk4LzMyMjI2MzQ2MS0xODVlMGQ1NC1mYWE4LTRmOWMtODQ1Yi1hMWMwYWE1MDMwYmQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTAyMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlMjNkZWRmYjIyMzY0M2NhZmQ5NTA0YmE5ZWQwZmY1MjI4MzVlNTExZTkzOGQ2NDhiMWZmMWNhMWUyZWRjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fGJIgvYYldu6aLguYKRyi1Pi0gTfV37J6cWwBrdUVwE) [ ![Apr-14-2024 16-09-28](https://private-user-images.githubusercontent.com/4551598/322263461-185e0d54-faa8-4f9c-845b-a1c0aa5030bd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTAzMjYsIm5iZiI6MTcxMzA5MDAyNiwicGF0aCI6Ii80NTUxNTk4LzMyMjI2MzQ2MS0xODVlMGQ1NC1mYWE4LTRmOWMtODQ1Yi1hMWMwYWE1MDMwYmQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTAyMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlMjNkZWRmYjIyMzY0M2NhZmQ5NTA0YmE5ZWQwZmY1MjI4MzVlNTExZTkzOGQ2NDhiMWZmMWNhMWUyZWRjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fGJIgvYYldu6aLguYKRyi1Pi0gTfV37J6cWwBrdUVwE) ](https://private-user-images.githubusercontent.com/4551598/322263461-185e0d54-faa8-4f9c-845b-a1c0aa5030bd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTAzMjYsIm5iZiI6MTcxMzA5MDAyNiwicGF0aCI6Ii80NTUxNTk4LzMyMjI2MzQ2MS0xODVlMGQ1NC1mYWE4LTRmOWMtODQ1Yi1hMWMwYWE1MDMwYmQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTAyMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlMjNkZWRmYjIyMzY0M2NhZmQ5NTA0YmE5ZWQwZmY1MjI4MzVlNTExZTkzOGQ2NDhiMWZmMWNhMWUyZWRjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fGJIgvYYldu6aLguYKRyi1Pi0gTfV37J6cWwBrdUVwE) [ ](https://private-user-images.githubusercontent.com/4551598/322263461-185e0d54-faa8-4f9c-845b-a1c0aa5030bd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTAzMjYsIm5iZiI6MTcxMzA5MDAyNiwicGF0aCI6Ii80NTUxNTk4LzMyMjI2MzQ2MS0xODVlMGQ1NC1mYWE4LTRmOWMtODQ1Yi1hMWMwYWE1MDMwYmQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTAyMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlMjNkZWRmYjIyMzY0M2NhZmQ5NTA0YmE5ZWQwZmY1MjI4MzVlNTExZTkzOGQ2NDhiMWZmMWNhMWUyZWRjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fGJIgvYYldu6aLguYKRyi1Pi0gTfV37J6cWwBrdUVwE)

thank you for the gif, it really helped me to understand the problem. I was able to reproduce the issue, it's basically due to this linking am I correct: `[[Not an icon|Not an Icon]]` (imagine the file `Not an Icon` has an icon it will place the icon before both names), so it results in:
<img width="270" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/20746070/3c23c836-df0d-4f19-8dff-a6a6f849e404">
<img width="145" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/20746070/41c5f5be-dd4c-42b2-90d7-cd3598530165">

**Comment by TarodBOFH** [comment]
Maybe related to this: I use metadata on my todo lists to track who should do what (like [owner:: [[Link to Someone]]] ;

If on a dataview query I display those todo tasks, they also have double icon.

i.e.: 

- Iconize: files in "People" folders have `FasPerson` icon

```markdown
# File Person A in a people Folder
... 
```

Another file with a todo
```markdown
- [ ] Do something important [owner:: [[Person A]]]
```

Third file with the query:
```dataview
TASK
```

First file renders ok, second file renders ok but third file has two icons in the link

**Comment by robatron** [comment]
FWIW, here's my silly workaround for this:

Since the bug occurs when the link _title_ is equal to the _filename_, e.g.,

> `[[💁‍♂️../../Profile/Someone Awesome|💁‍♂️Someone Awesome]]` → [💁‍♂️💁‍♂️Someone Awesome](#)

We can append a [U+200B Zero Width Space (ZWSP)](https://www.compart.com/en/unicode/U+200B) Unicode character to the title to break the equality:

> `[[💁‍♂️../../Profile/Someone Awesome|Someone Awesome​]]` → [💁‍♂️Someone Awesome](#)

The [obsidian-unicode-search](https://github.com/BambusControl/obsidian-unicode-search) plugin works well for this. (Be sure to enable "format control" characters in options.)
