### ISSUE TITLE
Icons not rendering correctly in Live Preview

### ISSUE THREAD

**Issue by ribena75** [FlorianWoelki/obsidian-iconize#446]
**Describe the bug**
Icons not rendering correctly in Live Preview anymore.
<img width="412" alt="live-preview" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/9573646/adac7223-c523-4abf-b5ba-100d626aff12">
<img width="421" alt="reading-mode" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/9573646/53e60877-c308-40f0-92a6-f462396a81c8">

**To Reproduce**
1. Updated Iconize plugin
2. Togge reading mode/live preview on a file with icons within the text

**Expected behavior**
Pretty sure the icons rendered fine in live preview in the previous version.

**Screenshots**
See attached.

**Comment by FlorianWoelki** [comment]
i think this is fixed with version [2.11.10](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.10). could also be related to #438.

**Comment by davidkopp** [comment]
The issue still exists with the new version [2.11.10](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.10).
