### ISSUE TITLE
Emojis non showing

### ISSUE THREAD

**Issue by Jaked2001** [FlorianWoelki/obsidian-iconize#458]
**Describe the bug**
Emojis in text in editing mode do not show

**To Reproduce**
It's unclear to me how to reproduce this, since it seems to have an irregular behavior. 
Anyhow, my notes seem to not be able to show emojis in the text.

**Expected behavior**
I expect to see emojis

**Additional context**
To problem seems to solve it self right way when disabling the iconize plugin
plugin version: 2.11.11

**Comment by FlorianWoelki** [comment]
> **Describe the bug**
> 
> Emojis in text in editing mode do not show
> 
> 
> 
> **To Reproduce**
> 
> It's unclear to me how to reproduce this, since it seems to have an irregular behavior. 
> 
> Anyhow, my notes seem to not be able to show emojis in the text.
> 
> 
> 
> 
> 
> **Expected behavior**
> 
> I expect to see emojis
> 
> 
> 
> 
> 
> **Additional context**
> 
> To problem seems to solve it self right way when disabling the iconize plugin
> 
> plugin version: 2.11.11
> 
> 

thanks for reporting. does it work if you set the option emoji mode in the Iconize settings to `native`?

**Comment by quanru** [comment]
I set the emoji mode to native, but the problem still exists.

**Comment by Medenor** [comment]
I have the same issue, I also tried to set the emoji mode to native, but the problem still exists.

**Comment by Jaked2001** [comment]
> thanks for reporting. does it work if you set the option emoji mode in the Iconize settings to native?

No. I never actually changed it from "native"

**Comment by Jaked2001** [comment]
> plugin version: 2.11.11 (but I already had the issue with the previous version)

Yeah, me too. It's been a problem for a couple of days at least

**Comment by frombrosis** [comment]
I have the same issue. It started occurring when the change was made in the plugin settings to ‘none’ to ‘default’ or similar. Before that change, it was working beautifully. For now, I have disabled this plugin unfortunately…

**Comment by m-beau** [comment]
Yeah all the emojis are broken across obsidian since the last iconize update!! It renders the package absolutely unusable!

**Comment by FlorianWoelki** [comment]
I need more information to reproduce the issue.

- Are there any error logs in the Developer Console?
- Is the problem still reproducible when you only have Iconize in your Vault without other plugins
- When does the error exactly occur?

**Comment by Stefanyeah** [comment]
I'm having the same problem.

**Is the problem still reproducible when you only have Iconize in your Vault without other plugins**
Switched off all plugins apart from Iconize and the problem presists. I'm using AnupPuccin as a theme.

**When does the error exactly occur?**
Almost always.
The icons are shown:
- in Dataview tables
- when the cursor is in the same line
- within callouts (unless I'm editing the callout. Then no icons are shown)

**Comment by pyxelr** [comment]
I have the same problem in Live Preview mode.

With Iconize `2.11.5`:

![2024-04-15_20-58-24](https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/194c67e0-a8a3-4dc5-8f7c-31351bf896e7)


After updating to the latest Iconize `2.11.11`, the same problem occurs on Windows, macOS, and Android:

![2024-04-15_21-00-16](https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/91370de8-aa1d-4f88-8c49-a31644812159)

Here is my default Iconize setup from `.obsidian/plugins/obsidian-icon-folder/data.json`:


```json
{
  "settings": {
    "migrated": 4,
    "iconPacksPath": ".obsidian/plugins/obsidian-icon-folder/icons",
    "fontSize": 16,
    "iconColor": null,
    "recentlyUsedIcons": [
      "🕑",
      "🧑‍🍳",
      "🍖",
      "🅿",
      "🥊"
    ],
    "recentlyUsedIconsSize": 5,
    "rules": [
      {
        "icon": "✅",
        "rule": "+LEARN 🚧/DATA SCIENCE 🚧/Courses 🚧/MATLAB 🚧/(YouTube) MATLAB Tutorial - Derek Banas 🚧.md\\/[\\w\\d\\s]+\\.(?:\\w+\\.)*\\w+",
        "for": "files",
        "order": 0,
        "useFilePath": true
      }
    ],
    "extraPadding": {
      "top": 2,
      "right": 2,
      "bottom": 2,
      "left": 2
    },
    "extraMargin": {
      "top": 0,
      "right": 4,
      "bottom": 0,
      "left": 0
    },
    "emojiStyle": "twemoji",
    "iconInTabsEnabled": true,
    "iconsBackgroundCheckEnabled": false,
    "iconInTitleEnabled": false,
    "iconInFrontmatterEnabled": false,
    "iconsInNotesEnabled": true,
    "iconIdentifier": ":",
    "iconsInLinksEnabled": true,
    "iconInFrontmatterFieldName": "icon",
    "iconColorInFrontmatterFieldName": "iconColor",
    "debugMode": false
  },
```

I cannot find anything interesting in the developer console. When I activate Iconize, there is only this single log line in the console:

```
loading iconize plugin:obsidian-icon-folder:5836 
```

**Comment by rotane** [comment]
Same issue, exactly as @Stefanyeah describes. Emojis only show up when my cursor is on the same line/block; in DataView blocks; and in Callouts (unless when editing).

I'm pretty much always in Live Preview.

Obsidian 1.5.12, Iconize 2.11.11

**Comment by Jaked2001** [comment]
I'm experiencing the problem just as @Stefanyeah described it. I am also using Anapuccin as a theme. I wonder if there might be some problem related to that (?)

**Comment by FlorianWoelki** [comment]
not entirely sure if the newest built version fixes this problem. i've tweaked some things. [this link](https://drive.google.com/file/d/1Y0koA2wSBn1rr6BDavc9U3M1dmev3umZ/view?usp=sharing) is the currently built version. it would be really nice, if someone could tell me if everything works fine or if there is still an issue.

here are the things you need to do to install the `main.js` file:
1. Go to your `.obsidian` folder (you can e.g., access that through Obsidian _Settings > Appearance > Themes (and click on the directory icon))
2. Go to the plugin directory (should be `.obsidian/plugins/obsidian-icon-folder/`)
3. Replace the main.js file with the newly downloaded `main.js` file

**Comment by Jaked2001** [comment]
@FlorianWoelki I have tried what you asked. It did seem to partially solve the problem. Emojis are displayed now, but it's like it's using some older version of the emojis (I'm not sure how it works, I'm not really into this stuff). For example, instead of a farmer is displaying a person followed by a crop, which is not the emojis I used:

![Schermata 2024-04-15 alle 21 27 18](https://github.com/FlorianWoelki/obsidian-iconize/assets/80152655/4d4b4dd6-1628-443b-bfb8-da248469a11a)

**Comment by pyxelr** [comment]
@FlorianWoelki: I also tried it.

Without Iconize:

![without](https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/e4ba6251-f934-437c-acc7-79f2400b0f4b)

With Iconize and modified `main.js`. Notice, that when I hover my cursor over emoji, there is a magnifier button and a preview is being shown. The same magnifier is being shown when I hover over images, although then a preview is not shown.

![with](https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/84edfa08-fb88-478b-a431-7ebb13e1c88e)

**Comment by FlorianWoelki** [comment]
thank you for the feedback @Jaked2001 and @pyxelr 

could you checkout [this one](https://drive.google.com/file/d/18ACGzQQpI3NiOcb3AxPqqfof7MTPxk0J/view?usp=sharing). I was also able to reproduce the example by @pyxelr but with this version I am not able to reproduce it anymore.

fyi: the old link is broken.

**Comment by Jaked2001** [comment]
Thank you for working on this right way trying to solve the issue. 

I've just tried the last version you sent and it seems to be working as expected! All emojis are displaying the way they should. 

Previus version:
![Schermata 2024-04-15 alle 21 27 18](https://github.com/FlorianWoelki/obsidian-iconize/assets/80152655/13d8e6ac-b423-47a7-86d9-0b69933fe2a2)

This version:
![Schermata 2024-04-15 alle 21 54 09](https://github.com/FlorianWoelki/obsidian-iconize/assets/80152655/9307a65e-278b-4653-8085-0ff5878dda22)

**Comment by ShadyLX** [comment]
@FlorianWoelki Hey, I had the same problem as @Jaked2001, your newest main.js fixed it completely for me, thanks!
I'm new to the plugin and have a somewhat similar question though: When using icons from icon packs, for example `:FabFonticonsFi:` it is not rendered while the cursor is within the same paragraph of text, it renders only when the cursor is elsewhere, is this intended behavior? It's not a big deal, but I figured I asked anyway. :)

**Comment by FlorianWoelki** [comment]
really awesome to hear that! thanks for all the great collaboration on that issue! I'll try to release a new version in the next few days.

> @FlorianWoelki Hey, I had the same problem as @Jaked2001, your newest main.js fixed it completely for me, thanks! I'm new to the plugin and have a somewhat similar question though: When using icons from icon packs, for example `:FabFonticonsFi:` it is not rendered while the cursor is within the same paragraph of text, it renders only when the cursor is elsewhere, is this intended behavior? It's not a big deal, but I figured I asked anyway. :)

yes, this is intended, but also a "bug". at least for now. I think, it is something similar to #315. feel free to upvote this one with a thumbs up.

**Comment by pyxelr** [comment]
@FlorianWoelki: For me, it does not seem to be fixed with the new `main.js`. Everything is the same as in my last comment.

**Comment by FlorianWoelki** [comment]
> @FlorianWoelki: For me, it does not seem to be fixed with the new `main.js`. Everything is the same as in my last comment. I can still see the magnifier button upon hovering and the emoji style is different.

yeah that's intended. sorry I was not aware of the magnifier there. but the tooltip always shows the "real" name of the emoji/icon. it's also described [here](https://florianwoelki.github.io/obsidian-iconize/good-to-know/see-icon-name.html).

**Comment by rotane** [comment]
> could you checkout [this one](https://drive.google.com/file/d/18ACGzQQpI3NiOcb3AxPqqfof7MTPxk0J/view?usp=sharing). I was also able to reproduce the example by @pyxelr but with this version I am not able to reproduce it anymore.

This does the trick for me as well. Thanks!

**Comment by FlorianWoelki** [comment]
the latest version [v2.11.12](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.12) should fix this issue.

**Comment by pyxelr** [comment]
@FlorianWoelki: `v2.11.12` still does not show up in my Obsidian community plugin updates (I have `v2.11.11`). Does it need to go through some verification process?

**Comment by FlorianWoelki** [comment]
> @FlorianWoelki: `v2.11.12` still does not show up in my Obsidian community plugin updates (I have `v2.11.11`). Does it need to go through some verification process?

normally, there is no verification process. I am also wondering why it is not updated. but, I cannot influence anything here.

**Comment by pyxelr** [comment]
@FlorianWoelki: Ok, I finally managed to get an update.

I see that `v2.11.12` partly resolved the issue.

Here is how it looks without Iconize (in live preview):

![without](https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/98894b38-0620-4f5e-800c-3df16f1079ae)

And here is how it looks with it:

![with](https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/49f13d3b-87c9-448a-a6f8-174a55060e1a)

When it is activated:
- emojis look differently. I would prefer the look as in the 1st screenshot in this message
- the 🏃‍♂️ (running_man) emoji is consisted of 2 emojis
- emojis are highlighted and get a magnifier icon on top of them

Lastly, I noticed something (not sure if it is from this version) that when I change the "emoji style" in Iconize settings, I get this ℹ️ icon at the top of the page, which I can get rid of by reopening the page:

![weird](https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/ec794802-f3f9-452d-9e2d-f2abec227c26)

**Comment by pyxelr** [comment]
Ah, I noticed that 🏃‍♂️ (running_man) emoji is being consisted of 2 emojis, when:

1. I turn off Iconize and have [emoji shortcodes](https://github.com/phibr0/obsidian-emoji-shortcodes) activated
2. I add a 🏃‍♂️ (running_man) emoji and turn on Iconize.

Now I removed Emoji shortcodes plugin, as its functionality was being duplicated by Iconize.

Nevertheless, I also noticed quite a weird behaviour in live preview mode while using Iconize. Emojis change their look when I hit enter:

![Obsidian_2024-04-18_22-29-58](https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/465b904e-e4cf-4b80-9f83-a9b647894c1d)

In "reading" mode they became brighter, while in "source mode" they look just like before hitting enter.

**Comment by FlorianWoelki** [comment]
> Ah, I noticed that 🏃‍♂️ (running_man) emoji is being consisted of 2 emojis, when:
> 
> 1. I turn off Iconize and have [emoji shortcodes](https://github.com/phibr0/obsidian-emoji-shortcodes) activated
> 2. I add a 🏃‍♂️ (running_man) emoji and turn on Iconize.
> 
> Now I removed Emoji shortcodes plugin, as its functionality was being duplicated by Iconize.
> 
> Nevertheless, I also noticed quite a weird behaviour in live preview mode while using Iconize. Emojis change their look when I hit enter (when I hit backspace (or when I hit space on the same line), the original look is brought back):
> 
> ![Obsidian_2024-04-18_22-35-56](https://private-user-images.githubusercontent.com/30161753/323753470-b6ad7e0a-b7e6-4a6e-84f6-f9376de9fd90.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDg1NzYsIm5iZiI6MTcxMzUwODI3NiwicGF0aCI6Ii8zMDE2MTc1My8zMjM3NTM0NzAtYjZhZDdlMGEtYjdlNi00YTZlLTg0ZjYtZjkzNzZkZTlmZDkwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA2MzExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZDBlZWNmYTJiMzE0NWEyNzYxZTZmMjJkN2U5Mzg4ZTc3NjQwNzFmYTFlMWE0ZGU3NWQ1ZTZlNTQ2YjRmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lDwmY64iBk9a1tSJJ8f_uSopHL34nWKRtTK5fg_LmaI) [ ![Obsidian_2024-04-18_22-35-56](https://private-user-images.githubusercontent.com/30161753/323753470-b6ad7e0a-b7e6-4a6e-84f6-f9376de9fd90.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDg1NzYsIm5iZiI6MTcxMzUwODI3NiwicGF0aCI6Ii8zMDE2MTc1My8zMjM3NTM0NzAtYjZhZDdlMGEtYjdlNi00YTZlLTg0ZjYtZjkzNzZkZTlmZDkwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA2MzExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZDBlZWNmYTJiMzE0NWEyNzYxZTZmMjJkN2U5Mzg4ZTc3NjQwNzFmYTFlMWE0ZGU3NWQ1ZTZlNTQ2YjRmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lDwmY64iBk9a1tSJJ8f_uSopHL34nWKRtTK5fg_LmaI) ](https://private-user-images.githubusercontent.com/30161753/323753470-b6ad7e0a-b7e6-4a6e-84f6-f9376de9fd90.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDg1NzYsIm5iZiI6MTcxMzUwODI3NiwicGF0aCI6Ii8zMDE2MTc1My8zMjM3NTM0NzAtYjZhZDdlMGEtYjdlNi00YTZlLTg0ZjYtZjkzNzZkZTlmZDkwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA2MzExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZDBlZWNmYTJiMzE0NWEyNzYxZTZmMjJkN2U5Mzg4ZTc3NjQwNzFmYTFlMWE0ZGU3NWQ1ZTZlNTQ2YjRmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lDwmY64iBk9a1tSJJ8f_uSopHL34nWKRtTK5fg_LmaI) [ ](https://private-user-images.githubusercontent.com/30161753/323753470-b6ad7e0a-b7e6-4a6e-84f6-f9376de9fd90.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDg1NzYsIm5iZiI6MTcxMzUwODI3NiwicGF0aCI6Ii8zMDE2MTc1My8zMjM3NTM0NzAtYjZhZDdlMGEtYjdlNi00YTZlLTg0ZjYtZjkzNzZkZTlmZDkwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA2MzExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZDBlZWNmYTJiMzE0NWEyNzYxZTZmMjJkN2U5Mzg4ZTc3NjQwNzFmYTFlMWE0ZGU3NWQ1ZTZlNTQ2YjRmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lDwmY64iBk9a1tSJJ8f_uSopHL34nWKRtTK5fg_LmaI)
> 
> In "reading" mode they became brighter, while in "source mode" they look just like before hitting enter.
> 
> This seems to be fixed when I turn off "Toogle icons while editing notes", but I also lose the option to easily add emojis with `:`.

this is generally the live preview mode. whenever you enter the line, it will revert back to the original emoji/icon. that's why you also see the `:CoFlag` (for instance) instead of the rendered emoji when you are in the line.

**Comment by pyxelr** [comment]
@FlorianWoelki: Thanks for explaining!

Well, to overcome this, I have installed [emoji shortcodes](https://github.com/phibr0/obsidian-emoji-shortcodes) and turned off "Toogle icons while editing notes" in Iconize settings. Otherwise, it was a little annoying to see the flashing emoji while editing text on the same line.

**Comment by FlorianWoelki** [comment]
> @FlorianWoelki: Thanks for explaining!
> 
> Well, to overcome this, I have installed [emoji shortcodes](https://github.com/phibr0/obsidian-emoji-shortcodes) and turned off "Toogle icons while editing notes" in Iconize settings. Otherwise, it was a little annoying to see the flashing emoji while editing text on the same line in live preview.

lovely stuff, I'll try to fix this. could you create a new issue with the wonderful gifs you've provided? thanks!

**Comment by pyxelr** [comment]
> > @FlorianWoelki: Thanks for explaining!
> > Well, to overcome this, I have installed [emoji shortcodes](https://github.com/phibr0/obsidian-emoji-shortcodes) and turned off "Toogle icons while editing notes" in Iconize settings. Otherwise, it was a little annoying to see the flashing emoji while editing text on the same line in live preview.
> 
> lovely stuff, I'll try to fix this. could you create a new issue with the wonderful gifs you've provided? thanks!

Sure! Here it is: https://github.com/FlorianWoelki/obsidian-iconize/issues/465.

**Comment by jmonroynieto** [comment]
I was using

**Comment by jmonroynieto** [comment]
I was using v2.11.12 (the latest available) and this problem is not resolved. You can see details of the issue on [this forum post](https://forum.obsidian.md/t/metadata-emoji-tags-dissapear-from-the-html-when-not-in-active-line/80483). I thought it was unrelated to pluggins since the call stack for the line that modifies the emojis only contains app.js functions.

Disabling this plugin solved my issue.
