### ISSUE TITLE
Typing in Obsidian is extremely slow with 2.14.2

### ISSUE THREAD

**Issue by dangle** [FlorianWoelki/obsidian-iconize#523]
**Describe the bug**
Upgrading to 2.14.2 makes typing in Obsidian unbearably slow. It takes a good five or six seconds after typing before anything shows up. Other Obsidian functionality seems fine.

**To Reproduce**
1. Upgrade to 2.14.2

**Expected behavior**
I expect to be able to type in Obsidian.

**Additional context**
1. This is happening on two separate machines.
2. This happens with no other plugins installed.
3. Disabling Iconize solves the issue.
4. Both machines are Arch Linux.
5. Both machines are using X with the proprietary NVIDIA drivers.
6. One machine is running GNOME, the other is running herbstluftwm.
7. Both are running Obsidian 1.6.7 with the installed base of 1.6.5.
8. Downgrading to 2.14.1 resolves the issue.

**EDIT**
Apparently, I hadn't updated my Windows machine's version of Iconize. It's having the same performance issues.

**Comment by DmiShib** [comment]
Same on macOS Sonoma, M1 Pro.

**Comment by spiritualgeek** [comment]
I'm experiencing the same issue:

- Obsidian version: v1.6.7
- Installer version: v1.6.7
- Sonoma 14.6
- M1 Studio with 32GB 

cc @FlorianWoelki

**Comment by spiritualgeek** [comment]
Please also see #534

**Comment by FlorianWoelki** [comment]
I think this is related to #602, which was fixed recently.

**Comment by dangle** [comment]
This is still an issue in 2.14.5. Is the fix in that release?

**Comment by dangle** [comment]
Here is a [recording](https://github.com/user-attachments/assets/c3153831-d6cb-4da4-afdf-6f86691b4995) of the issue with 2.14.5.

It does seem to be better. This one only has the two icons in it, but it gets worse with more (and better with less).

It's still fairly unusable though, IMO.

**Comment by dangle** [comment]
I hadn't been able to test this in quite a while, but it seems to be working fine now that I've finally re-enabled it.

**Comment by sisi-sh** [comment]
I'm still encountering this issue on plugin ver. 2.14.7 on Obsidian 1.8.10 on all of my devices (iOS, Linux, Windows). 

This only happens when I have "Show icon in links" on, which is unfortunate, because I only have like 8 files tagged with an icon. It seems to worsen by a lot in files that have a lot of links and/or a Pixel banner in them, but those notes all run flawlessly with the option disabled. Having "use icons in text" on doesn't influence it at all. 

Am I the only one?
